networks:
  backnrun:

services:
  golang:
    image: mcr.microsoft.com/devcontainers/go:1-1.24-bookworm
    container_name: backnrun_dev
    working_dir: /go/src/backnrun
    volumes:
      - ./:/go/src/backnrun
      - ./.docker/go/bin:/go/bin
      - ./.docker/go/pkg:/go/pkg
    environment:
      - TZ=America/Belem
    networks:
      - backnrun
    tty: true
    restart: on-failure